#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : Exercice2_bd.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Aug 01 01:50:45 -0400 2022
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: Exercice2_bd.sh [-help]
# usage: Exercice2_bd.sh [-lib_map_path]
# usage: Exercice2_bd.sh [-noclean_files]
# usage: Exercice2_bd.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'Exercice2_bd.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 axi_lite_ipif_v3_0_4 v_tc_v6_2_1 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_11 xlconstant_v1_1_7 smartconnect_v1_0 axi_register_slice_v2_1_22 v_vscaler_v1_1_0 v_hscaler_v1_1_0 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_22 axis_subset_converter_v1_1_22 interrupt_control_v3_1_4 axi_gpio_v2_0_24 axis_data_fifo_v2_0_4 xlslice_v1_0_2)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "Exercice2_bd.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_processing_system7_0_0/sim/Exercice2_bd_processing_system7_0_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_clk_wiz_0_0/Exercice2_bd_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_clk_wiz_0_0/Exercice2_bd_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_proc_sys_reset_0_0/sim/Exercice2_bd_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_tc_0_1/sim/Exercice2_bd_v_tc_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_axi4s_vid_out_0_0/sim/Exercice2_bd_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d57c/src/ClockGen.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d57c/src/SyncAsync.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d57c/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d57c/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d57c/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d57c/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d57c/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_rgb2dvi_0_0/sim/Exercice2_bd_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_0/sim/bd_c788_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/sim/bd_c788_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_2/sim/bd_c788_arinsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_3/sim/bd_c788_rinsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_4/sim/bd_c788_awinsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_5/sim/bd_c788_winsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_6/sim/bd_c788_binsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_7/sim/bd_c788_aroutsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_8/sim/bd_c788_routsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_9/sim/bd_c788_awoutsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_10/sim/bd_c788_woutsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_11/sim/bd_c788_boutsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_12/sim/bd_c788_arni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_13/sim/bd_c788_rni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_14/sim/bd_c788_awni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_15/sim/bd_c788_wni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_16/sim/bd_c788_bni_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ea34/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_17/sim/bd_c788_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_18/sim/bd_c788_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8047/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_19/sim/bd_c788_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_20/sim/bd_c788_s00a2s_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_21/sim/bd_c788_sarn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_22/sim/bd_c788_srn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_23/sim/bd_c788_sawn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_24/sim/bd_c788_swn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_25/sim/bd_c788_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_26/sim/bd_c788_m00s2a_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_27/sim/bd_c788_m00arn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_28/sim/bd_c788_m00rn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_29/sim/bd_c788_m00awn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_30/sim/bd_c788_m00wn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_31/sim/bd_c788_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/7bd7/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_32/sim/bd_c788_m00e_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_33/sim/bd_c788_m01s2a_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_34/sim/bd_c788_m01arn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_35/sim/bd_c788_m01rn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_36/sim/bd_c788_m01awn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_37/sim/bd_c788_m01wn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_38/sim/bd_c788_m01bn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_39/sim/bd_c788_m01e_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_40/sim/bd_c788_m02s2a_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_41/sim/bd_c788_m02arn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_42/sim/bd_c788_m02rn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_43/sim/bd_c788_m02awn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_44/sim/bd_c788_m02wn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_45/sim/bd_c788_m02bn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_46/sim/bd_c788_m02e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/sim/bd_c788.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_0/sim/bd_f134_smartconnect_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_vscaler_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/hdl/v_vscaler_v1_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/sim/bd_f134_vsc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_hscaler_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/hdl/v_hscaler_v1_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/sim/bd_f134_hsc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tdata_bd_f134_input_size_set_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tuser_bd_f134_input_size_set_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tstrb_bd_f134_input_size_set_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tkeep_bd_f134_input_size_set_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tid_bd_f134_input_size_set_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tdest_bd_f134_input_size_set_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/tlast_bd_f134_input_size_set_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/69d9/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/hdl/top_bd_f134_input_size_set_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/sim/bd_f134_input_size_set_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/sim/bd_f134_rst_axis_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/sim/bd_f134_reset_sel_axis_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_6/sim/bd_f134_axis_register_slice_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/abd4/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_7/sim/bd_f134_axis_fifo_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_8/sim/bd_f134_xlslice_0_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_9/sim/bd_f134_xlslice_1_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/sim/bd_f134.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/sim/Exercice2_bd_v_proc_ss_0_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_0/sim/bd_8e83_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_1/sim/bd_8e83_psr0_0.vhd" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_2/sim/bd_8e83_psr_aclk_0.vhd" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_3/sim/bd_8e83_psr_aclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_4/sim/bd_8e83_arinsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_5/sim/bd_8e83_rinsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_6/sim/bd_8e83_awinsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_7/sim/bd_8e83_winsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_8/sim/bd_8e83_binsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_9/sim/bd_8e83_aroutsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_10/sim/bd_8e83_routsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_11/sim/bd_8e83_awoutsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_12/sim/bd_8e83_woutsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_13/sim/bd_8e83_boutsw_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_14/sim/bd_8e83_arni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_15/sim/bd_8e83_rni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_16/sim/bd_8e83_awni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_17/sim/bd_8e83_wni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_18/sim/bd_8e83_bni_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_19/sim/bd_8e83_s00mmu_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_20/sim/bd_8e83_s00tr_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_21/sim/bd_8e83_s00sic_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_22/sim/bd_8e83_s00a2s_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_23/sim/bd_8e83_sarn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_24/sim/bd_8e83_srn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_25/sim/bd_8e83_sawn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_26/sim/bd_8e83_swn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_27/sim/bd_8e83_sbn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_28/sim/bd_8e83_m00s2a_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_29/sim/bd_8e83_m00arn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_30/sim/bd_8e83_m00rn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_31/sim/bd_8e83_m00awn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_32/sim/bd_8e83_m00wn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_33/sim/bd_8e83_m00bn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_34/sim/bd_8e83_m00e_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_35/sim/bd_8e83_m01s2a_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_36/sim/bd_8e83_m01arn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_37/sim/bd_8e83_m01rn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_38/sim/bd_8e83_m01awn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_39/sim/bd_8e83_m01wn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_40/sim/bd_8e83_m01bn_0.sv" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_41/sim/bd_8e83_m01e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/sim/bd_8e83.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/sim/Exercice2_bd_smartconnect_0_0.v" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_testPatternGenerator_0_0/sim/Exercice2_bd_testPatternGenerator_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/Exercice2_bd/ipshared/e88b/src/mycolorRegister_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/Exercice2_bd/ipshared/e88b/src/mycolorRegister_v1_0.vhd" \
    "$ref_dir/../../../bd/Exercice2_bd/ip/Exercice2_bd_myColorRegister_1_1/sim/Exercice2_bd_myColorRegister_1_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/d0f7" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/25b7/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/896c/hdl/verilog" +incdir+"$ref_dir/../../../../Atelier2.gen/sources_1/bd/Exercice2_bd/ipshared/8713/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/Exercice2_bd/sim/Exercice2_bd.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.Exercice2_bd xil_defaultlib.glbl -o Exercice2_bd_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./Exercice2_bd_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./Exercice2_bd.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key Exercice2_bd_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc Exercice2_bd_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./Exercice2_bd.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: Exercice2_bd.sh [-help]\n\
Usage: Exercice2_bd.sh [-lib_map_path]\n\
Usage: Exercice2_bd.sh [-reset_run]\n\
Usage: Exercice2_bd.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
