# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Workspace/Atelier2/Atelier2.runs/synth_1/Exercice2_bd_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Workspace/Atelier2/Atelier2.cache/wt [current_project]
set_property parent.project_path C:/Workspace/Atelier2/Atelier2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo-z7-10:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Workspace/Atelier2/Atelier2.ip_defs/rgb2dvi
  c:/Workspace/Atelier2/Atelier2.ip_defs/myColorRegister_1.0
  c:/Workspace/Atelier2/Atelier2.ip_defs/tmds_v1_0
  c:/Workspace/Atelier2/lib/graphics
  c:/Workspace/Atelier2/lib/vivado
  c:/Workspace/Atelier2/lib/vivado-boards-master
  c:/Workspace/Atelier2/lib/vivado-library
} [current_project]
update_ip_catalog
set_property ip_output_repo c:/Workspace/Atelier2/Atelier2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib C:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/hdl/Exercice2_bd_wrapper.v
read_vhdl -library xil_defaultlib C:/Workspace/Atelier2/Atelier2.srcs/sources_1/imports/new/testPatternGenerator.vhd
add_files C:/Workspace/Atelier2/Atelier2.srcs/sources_1/bd/Exercice2_bd/Exercice2_bd.bd
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_processing_system7_0_0/Exercice2_bd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_clk_wiz_0_0/Exercice2_bd_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_clk_wiz_0_0/Exercice2_bd_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_clk_wiz_0_0/Exercice2_bd_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_proc_sys_reset_0_0/Exercice2_bd_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_proc_sys_reset_0_0/Exercice2_bd_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_tc_0_1/Exercice2_bd_v_tc_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_axi4s_vid_out_0_0/Exercice2_bd_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/bd_c788_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_1/bd_c788_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_2/bd_c788_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_3/bd_c788_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_4/bd_c788_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_5/bd_c788_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_6/bd_c788_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_7/bd_c788_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_8/bd_c788_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_9/bd_c788_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_10/bd_c788_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_11/bd_c788_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_12/bd_c788_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_13/bd_c788_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_14/bd_c788_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_15/bd_c788_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_16/bd_c788_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_20/bd_c788_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_21/bd_c788_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_22/bd_c788_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_23/bd_c788_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_24/bd_c788_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_25/bd_c788_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_26/bd_c788_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_27/bd_c788_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_28/bd_c788_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_29/bd_c788_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_30/bd_c788_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_31/bd_c788_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_33/bd_c788_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_34/bd_c788_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_35/bd_c788_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_36/bd_c788_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_37/bd_c788_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_38/bd_c788_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_40/bd_c788_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_41/bd_c788_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_42/bd_c788_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_43/bd_c788_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_44/bd_c788_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_1/ip/ip_45/bd_c788_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_1/bd_f134_vsc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_2/bd_f134_hsc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_3/bd_f134_input_size_set_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/bd_f134_rst_axis_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_4/bd_f134_rst_axis_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_f134_reset_sel_axis_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_f134_reset_sel_axis_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_5/bd_f134_reset_sel_axis_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/ip/ip_6/bd_f134_axis_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_v_proc_ss_0_0/bd_0/bd_f134_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_8e83_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_8e83_psr0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_8e83_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_8e83_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_8e83_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_8e83_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_8e83_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_8e83_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_8e83_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_8e83_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_8e83_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_8e83_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_8e83_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_8e83_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_8e83_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_13/bd_8e83_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_14/bd_8e83_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_15/bd_8e83_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_8e83_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_8e83_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_8e83_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_22/bd_8e83_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_8e83_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_8e83_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_8e83_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_8e83_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_8e83_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_8e83_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_29/bd_8e83_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_30/bd_8e83_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_31/bd_8e83_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_32/bd_8e83_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_8e83_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_35/bd_8e83_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_36/bd_8e83_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_37/bd_8e83_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_38/bd_8e83_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_8e83_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_8e83_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_42/bd_8e83_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_43/bd_8e83_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_44/bd_8e83_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_45/bd_8e83_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_46/bd_8e83_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_47/bd_8e83_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_49/bd_8e83_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_50/bd_8e83_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_51/bd_8e83_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_52/bd_8e83_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_53/bd_8e83_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_54/bd_8e83_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_56/bd_8e83_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_57/bd_8e83_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_58/bd_8e83_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_59/bd_8e83_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_60/bd_8e83_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/bd_0/ip/ip_61/bd_8e83_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_axi_gpio_0_0/Exercice2_bd_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_axi_gpio_0_0/Exercice2_bd_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_axi_gpio_0_0/Exercice2_bd_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_axi_gpio_0_0/PmodJSTK2_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_axi_gpio_0_0/PmodJSTK2_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_axi_gpio_0_0/PmodJSTK2_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/Exercice2_bd_PmodJSTK2_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_pmod_bridge_0_0/PmodJSTK2_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/ip/Exercice2_bd_PmodJSTK2_0_2/src/PmodJSTK2_axi_quad_spi_0_0/PmodJSTK2_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Workspace/Atelier2/Atelier2.gen/sources_1/bd/Exercice2_bd/Exercice2_bd_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Workspace/Atelier2/Atelier2.srcs/constrs_1/imports/new/atelier4Constraints.xdc
set_property used_in_implementation false [get_files C:/Workspace/Atelier2/Atelier2.srcs/constrs_1/imports/new/atelier4Constraints.xdc]

read_xdc C:/Workspace/Atelier2/Atelier2.srcs/constrs_1/new/Zybo-Z7-master.xdc
set_property used_in_implementation false [get_files C:/Workspace/Atelier2/Atelier2.srcs/constrs_1/new/Zybo-Z7-master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
OPTRACE "compile_c" START { }
compile_c [get_files C:/Workspace/Atelier2/Atelier2.srcs/sources_1/bd/Exercice2_bd/Exercice2_bd.bd
]
OPTRACE "compile_c" END { }
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Exercice2_bd_wrapper -part xc7z010clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Exercice2_bd_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Exercice2_bd_wrapper_utilization_synth.rpt -pb Exercice2_bd_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
